### ISSUE TITLE
BUG: Memory Error and T-side simulation continues beyond specified end time

### ISSUE THREAD

**Issue by rozan977** [tdcosim/TDcoSim#13]
**Describe the bug**
 The simulation throws a memory error and doesn't end at the end time specified on the config file.
**To Reproduce**
The config had 33 distribution system with the following configuration:
				{
                    "nodenumber": 117,
                    "filePath": ["..\\SampleData\\DNetworks\\123Bus\\case123ZIP.dss"],
                    "solarFlag":1,
                    "solarPenetration":0.2,
                    "DERParameters":{
                        "pvderScale": 1,
                        "V_LV0": 0.50,   
                        "V_LV1": 0.70,
                        "V_LV2": 0.88,
                        "t_LV0_limit": 0.04,  
                        "t_LV1_limit": 0.05,  
                        "t_LV2_limit": 0.06,
                        "V_HV1":1.15,
                        "V_HV2":1.20,
                        "t_HV1_limit": 3.0,
                        "t_HV2_limit": 0.016,
                        "VRT_INSTANTANEOUS_TRIP": false,
                        "VRT_MOMENTARY_CESSATION": false,
                        "OUTPUT_RESTORE_DELAY": 0.5,
                        "power_rating":50,
                        "SteadyState":true
                    }
                }

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50960766/69261470-3a033280-0b87-11ea-8a62-84938cc2689e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - PSS/E Version [e.g. 33.3.0]

PSSE/E version 33.3.0 is used

**Additional context**

**Comment by sibyjackgrove** [comment]
I wanted to check whether this failure had something to do with wrong frequency information in the PV-DER model. So I did a co-simulation using @rozan977 config file (with 33 feeders) after enabling the frequency estimation from the phase angle flag for the PV-DER model. However, I am still getting the same error.

**Comment by yim0331** [comment]
This issue occurs by the out of memory size of the computer comparing to the size of the "S" values. You can check our server computer. 

When I tested in the machine, it does not occur.

**Comment by yim0331** [comment]
@sibyjackgrove Were you able to test the code according to this issue? I have no chance to run the memory error fix code due to the PSSE license issue. Please let me know the test result.

**Comment by sibyjackgrove** [comment]
Resolve with commit 0d422d208059353030a87815938c67918c766991, e4e79ae3a0905ad3178228e0d56e219cc3e968d5
