### ISSUE TITLE
Feature request: Ability to manually specify location of DERs in the feeder

### ISSUE THREAD

**Issue by rozan977** [tdcosim/TDcoSim#15]
**Is your feature request related to a problem? Please describe.**

To be able to parameterize DER_A model and other aggregated positive sequence model based studies, TDcoSIm should have a feature that allows users to decide the locations of DERs in the distribution feeder.

**Describe the solution you'd like**
A possible solution to this is to allow user access to the random seed variable or modify config file to provide location of DERs within distribution feeder.

**Comment by sibyjackgrove** [comment]
Option to manually specify nodes as a list of strings using the "**PVPlacement**" field in config file was added with 9fcdea93d3ad6cd5dc1c90e33fdf87b4e4ee3660.
For details on usage refer: https://github.com/tdcosim/TDcoSim/blob/master/docs/user_guide/user_guide_understanding_config.md
