### ISSUE TITLE
Making TDCosim compatible with PSS/E 34

### ISSUE THREAD

**Issue by syedrizvi89** [tdcosim/TDcoSim#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by yim0331** [comment]
Hi, TDCoSim is tested with PSSE34. The installation and dependency information is available at https://github.com/tdcosim/TDcoSim/blob/v2.0.0rc2_dev/docs/user_guide/user_guide_installation.md

Thanks,
