### ISSUE TITLE
User Guide Update

### ISSUE THREAD

**Issue by yim0331** [tdcosim/TDcoSim#32]
tdcosim_User_Manual.pdf:
2019 Aug 23rd Version -> new version (version 1.0.0)
a. Project lead: Ning Kang
b. What are the inputs: Add DER detail information
c. Accessing the results: change: "the same folder as tdcosimapp.py" -> "the folder under results"
d. PSSE configuration: add PSSE location property
e. OpenDSS + DER configuration: add DER config file property
f. Change the examples config.json format

user_guide.md:
Add DER config information to the 

API document: The function and parameter information should be added

**Comment by sibyjackgrove** [comment]
User guide was updated in a0080c87dfc9f36e545799e14dc4e70359079d1d.
